spring:
  application:
    name: spring-auth
  datasource:
    username: root
    password: pass123
    url: jdbc:mysql://localhost:3306/login_system

  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
    springframework:
      security: DEBUG
